# Generated by Django 6.1 on 2026-08-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=255, unique=True)),
                ('framework', models.CharField(max_length=50)),
                ('is_connected', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Span',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('span_id', models.CharField(max_length=64, unique=True)),
                ('trace_id', models.CharField(db_index=True, max_length=64)),
                ('parent_span_id', models.CharField(blank=True, max_length=64, null=True)),
                ('name', models.CharField(max_length=255)),
                ('app_name', models.CharField(max_length=255)),
                ('start_time', models.FloatField(null=True)),
                ('end_time', models.FloatField(null=True)),
                ('duration_ms', models.FloatField(null=True)),
                ('status', models.CharField(default='in_progress', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
